# Ejercicio - Dimensionality Curse
## José Fernando Valdizón - 17012696

In [2]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures

In [4]:
#Creating data set
x = np.arange(8).reshape(4, 2)
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

#### Fitting with Different Polynomial grades

In [6]:
#Grade 1
pol = PolynomialFeatures(1)
n= pol.fit_transform(x)
#Expected = [1,a,b]
n

array([[1., 0., 1.],
       [1., 2., 3.],
       [1., 4., 5.],
       [1., 6., 7.]])

In [7]:
n.shape

(4, 3)

In [8]:
#Grade 2
pol = PolynomialFeatures(2)
n = pol.fit_transform(x)
#Expected = [1,a,b, a^2, ab, b^2]
n

array([[ 1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5., 16., 20., 25.],
       [ 1.,  6.,  7., 36., 42., 49.]])

In [9]:
n.shape

(4, 6)

In [10]:
#Grade 3
pol = PolynomialFeatures(3)
n = pol.fit_transform(x)
#Expected = [1,a,b, a^2, ab, b^2, a^3, a^2b, ab^2, b^3]
n

array([[  1.,   0.,   1.,   0.,   0.,   1.,   0.,   0.,   0.,   1.],
       [  1.,   2.,   3.,   4.,   6.,   9.,   8.,  12.,  18.,  27.],
       [  1.,   4.,   5.,  16.,  20.,  25.,  64.,  80., 100., 125.],
       [  1.,   6.,   7.,  36.,  42.,  49., 216., 252., 294., 343.]])

In [14]:
n.shape
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [19]:
#With interaction
pol = PolynomialFeatures(interaction_only=True)
n = pol.fit_transform(x)
#Expected = [1, a, b, ab]
n
#Ommits x**d values

array([[ 1.,  0.,  1.,  0.],
       [ 1.,  2.,  3.,  6.],
       [ 1.,  4.,  5., 20.],
       [ 1.,  6.,  7., 42.]])

In [13]:
n.shape

(4, 4)

Dimensionality Curse is related to the complexity that grows exponentially as we increase the number of features and the degree of the fitting line. As I investigated, the possible number features can grow as high as C(n+d,d), which means the combination of n+d elements combined in groups of size d. (n+d)!/d!.

The intuition as of why is more complex as the features count increase is related to the fact that the space where the data points lie, gets exponentilly wider and therefore, it is harder to see a concentration of points that denotes a pattern or a trend, which is essential to build ML models. 